/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-common-conventions")
}

dependencies {
    implementation("io.projectreactor:reactor-core:3.8.3")
    implementation("io.projectreactor:reactor-test:3.8.3")
    implementation("org.assertj:assertj-core:3.27.7")
}

