/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

val libs = extensions.getByType(VersionCatalogsExtension::class.java).named("libs")

dependencies{

    // Use JUnit Jupiter for testing.
    testImplementation(platform(libs.findLibrary("junit-bom").get()))

    testImplementation(libs.findLibrary("junit-jupiter").get())
    testRuntimeOnly(libs.findLibrary("junit-platform").get())
}