/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}


repositories {

    maven {
        url = uri("https://maven.aliyun.com/repository/public")
    }

    mavenCentral()
}


val libs = extensions.getByType(VersionCatalogsExtension::class.java).named("libs")

configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation(libs.findLibrary("commons-text").get())
    }
    annotationProcessor(libs.findLibrary("lombok").get())
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
